### ISSUE TITLE
Share in greasyfork.org

### ISSUE THREAD

**Issue by gabrielsmenezes** [bumbeishvili/create-branch-from-issue#21]
You probably know but it is possible to make code installation available through greasyfork.org. Thus, to install it is necessary only one click, as shown in the figure below:

![image](https://user-images.githubusercontent.com/40703319/110819494-9f8b9e80-8264-11eb-8f9a-1ec2f84f179e.png)

**Comment by gabrielsmenezes** [comment]
![image](https://user-images.githubusercontent.com/40703319/110819721-d3ff5a80-8264-11eb-847f-eb9434668f5c.png)

**Comment by gabrielsmenezes** [comment]
Congratularions, its a very usefull tool!

**Comment by bumbeishvili** [comment]
I know, though I think it's not sophisticated enough yet, to share it to a Greasyfork, still waiting for people`s feedback about it
